/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.BoxLayout;

/**
 *
 * @author joshd
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarsPane = new javax.swing.JPanel();
        EarthPane = new javax.swing.JPanel();
        Human = new javax.swing.JLabel();
        Cow = new javax.swing.JLabel();
        Lion = new javax.swing.JLabel();
        Grain = new javax.swing.JLabel();
        ShipImage = new javax.swing.JLabel();
        SwapBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MarsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MarsPane.setLayout(new javax.swing.BoxLayout(MarsPane, javax.swing.BoxLayout.LINE_AXIS));

        EarthPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Human.setText("HUMAN PLACEHOLDER");

        Cow.setText("COW PLACEHOLDER");

        Lion.setText("LION PLACEHOLDER");

        Grain.setText("GRAIN PLACEHOLDER");

        javax.swing.GroupLayout EarthPaneLayout = new javax.swing.GroupLayout(EarthPane);
        EarthPane.setLayout(EarthPaneLayout);
        EarthPaneLayout.setHorizontalGroup(
            EarthPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EarthPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(EarthPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Human)
                    .addComponent(Cow)
                    .addComponent(Lion)
                    .addComponent(Grain))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        EarthPaneLayout.setVerticalGroup(
            EarthPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EarthPaneLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(Human)
                .addGap(46, 46, 46)
                .addComponent(Grain)
                .addGap(50, 50, 50)
                .addComponent(Cow)
                .addGap(57, 57, 57)
                .addComponent(Lion)
                .addContainerGap())
        );

        ShipImage.setText("PLACEHOLDER");

        SwapBtn.setText("PLACEHOLDER FOR BUTTON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EarthPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(ShipImage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(SwapBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(MarsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EarthPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MarsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(ShipImage)
                .addGap(35, 35, 35)
                .addComponent(SwapBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cow;
    private javax.swing.JPanel EarthPane;
    private javax.swing.JLabel Grain;
    private javax.swing.JLabel Human;
    private javax.swing.JLabel Lion;
    private javax.swing.JPanel MarsPane;
    private javax.swing.JLabel ShipImage;
    private javax.swing.JLabel SwapBtn;
    // End of variables declaration//GEN-END:variables
}
